Repository Femme-js/Hoaxify, pull requests merged in 2021-02, with the labels that each got.

#33 added a trained model
  ANN_model/Initial Modeling_uni_bi_tri_grams.ipynb
  ANN_model/Initial_Model_Run_W2V.ipynb
  ANN_model/LDA Visualization.ipynb
  ANN_model/create_credible_file_structures_and_convert_articles_requests_to_json.ipynb
  ANN_model/real_news_data_and_fake_news_corpus_prep.ipynb
Labels: DWOC, level 5

#36 Update README.md
  README.md
Labels: DWOC, Level 3

#39 .gitignore added
  .gitignore
Labels: Level 2

#42 Auto assign
  .github/auto_assign.yml
  .github/workflows/reviewer_auto_assigner.yml
Labels: DWOC, Level 2
