Repository Femme-js/Hoaxify, pull requests merged in 2021-01, with the labels that each got.

#21 Added config file for Welcome BOT
  .github/config.yml
Labels: DWOC, Level 2

#24 Updated readme
  README.md
Labels: DWOC, Level 2

#22 added opensource programs section and code_of_conduct link to readme
  README.md
Labels: DWOC, Level 1

#23 ISSUE AND PR TEMPLATE
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/custom.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/pull_request_template.md
Labels: DWOC, Level 3

#26 Add Contributors Table in README.md
  README.md
Labels: DWOC, Level 2

#28 Update README.md
  README.md
Labels: DWOC, Level 1

#29 SVC and SGDClassifier Added
  Final.ipynb
Labels: DWOC, Level 4
